---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# riattrition

<!-- badges: start -->
<!-- badges: end -->

## Overview

The package provides a set of functions for conducting randomization inference in randomized experiments with sample attrition. It constructs valid p-values and confidence intervals for testing sharp null hypotheses and quantiles of individual treatment effects when outcomes are missing for some units. The package accommodates a range of missingness mechanisms, including general, monotone, sharp, and missing-at-random mechanisms.

## Installation

`riattrition` can be installed from its GitHub repository via

``` r
devtools::install_github("peizansheng/riattrition")
```

## Main Functions

This package provides the following functions to conduct randomization inference with sample attrition.

### Functions for Testing Sharp Null Hypothesis

- `pval_sharp()` obtains the p-value for testing the sharp null hypothesis $H_0: \tau = c$.
- `pval_sharp_twostep()` obtains the p-value for testing the sharp null hypothesis $H_0: \tau = c$ using the two-step procedure.
- `ci_sharp()` obtains one-sided or two-sided confidence interval assuming constant treatment effect.

### Functions for Testing Quantiles of Individual Treatment Effects

- `pval_quantile()` obtains the p-value for testing the null hypothesis $H_{k,c}: \tau_{(k)} \leq c$, where $\tau_{(k)}$ denotes individual treatment effect at rank $k$.
- `ci_quantile()` obtains one-sided confidence intervals for all quantiles of individual treatment effects.

```r
library(riattrition)
?pval_sharp
?pval_sharp_twostep
?ci_sharp
?pval_quantile
?ci_quantile
```

## Usage
We will use a simulated data to illustrate the usage of the main functions.
```r
set.seed(1)
N <- 500
Y0 <- rnorm(N, 0, 1)
Y1 <- Y0

# (1) Threshold Missingness
set.seed(1)
M0 <- as.numeric(Y0 <= qnorm(0.95))
M1 <- as.numeric(Y1 >= qnorm(0.05))
Z <- sample(c(rep(1, N/2), rep(0, N/2)))
M <- Z * M1 + (1 - Z) * M0
Y <- Z * Y1 + (1 - Z) * Y0 # No missing value
Y_observed <- ifelse(M == 0, NA, Y)
p_value_g <- pval_sharp(Z, Y_observed, c = 0, missing = "general", MWU = FALSE,
                        method.list = list(name = "Wilcoxon"),
                        stat.null = NULL, Z.perm = NULL, nperm = 10^4)
p_value_g_twostep <- pval_sharp_twostep(Z, Y_observed, c = 0, missing = "general",
                                        method.list = list(name = "Wilcoxon"),
                                        stat.null = NULL, Z.perm = NULL, nperm = 10^4, beta = 0.1 * 0.1)

# (2) Monotone Positive Missingness
set.seed(1)
M0 <- as.numeric(Y0 <= qnorm(0.92))
M1 <- as.numeric(Y0 <= qnorm(0.98))
Z <- sample(c(rep(1, N/2), rep(0, N/2)))
M <- Z * M1 + (1 - Z) * M0
Y <- Z * Y1 + (1 - Z) * Y0 # No missing value
Y_observed <- ifelse(M == 0, NA, Y)
p_value_mp <- pval_sharp(Z, Y_observed, c = 0, missing = "mp", MWU = FALSE,
                         method.list = list(name = "Wilcoxon"),
                         stat.null = NULL, Z.perm = NULL, nperm = 10^4)
p_value_mp_twostep <- pval_sharp_twostep(Z, Y_observed, c = 0, missing = "mp",
                                        method.list = list(name = "Wilcoxon"),
                                        stat.null = NULL, Z.perm = NULL, nperm = 10^4, beta = 0.1 * 0.1)

# (3) Monotone Negative Missingness
set.seed(1)
M1 <- as.numeric(Y0 >= qnorm(0.08))
M0 <- as.numeric(Y0 >= qnorm(0.02))
Z <- sample(c(rep(1, N/2), rep(0, N/2)))
M <- Z * M1 + (1 - Z) * M0
Y <- Z * Y1 + (1 - Z) * Y0 # No missing value
Y_observed <- ifelse(M == 0, NA, Y)
p_value_mn <- pval_sharp(Z, Y_observed, c = 0, missing = "mn", MWU = FALSE,
                         method.list = list(name = "Wilcoxon"),
                         stat.null = NULL, Z.perm = NULL, nperm = 10^4)
p_value_mn_twostep <- pval_sharp_twostep(Z, Y_observed, c = 0, missing = "mn",
                                         method.list = list(name = "Wilcoxon"),
                                         stat.null = NULL, Z.perm = NULL, nperm = 10^4, beta = 0.1 * 0.1)
                                         
# (4) Sharp Missingness
set.seed(1)
M0 <- as.numeric(Y0 <= qnorm(0.95))
M1 <- M0
Z <- sample(c(rep(1, N/2), rep(0, N/2)))
M <- Z * M1 + (1 - Z) * M0
Y <- Z * Y1 + (1 - Z) * Y0 # No missing value
Y_observed <- ifelse(M == 0, NA, Y)
p_value_s <- pval_sharp(Z, Y_observed, c = 0, missing = "sharp", MWU = FALSE,
                        method.list = list(name = "Wilcoxon"),
                        stat.null = NULL, Z.perm = NULL, nperm = 10^4)

# (5) Missing at random
set.seed(1)
p <- 0.95
M0 <- rbinom(N, 1, p)
M1 <- rbinom(N, 1, p)
Z <- sample(c(rep(1, N/2), rep(0, N/2)))
M <- Z * M1 + (1 - Z) * M0
Y <- Z * Y1 + (1 - Z) * Y0 # No missing value
Y_observed <- ifelse(M == 0, NA, Y)
p_value_r <- pval_sharp(Z, Y_observed, c = 0, missing = "random", MWU = FALSE,
                        method.list = list(name = "Wilcoxon"),
                        stat.null = NULL, Z.perm = NULL, nperm = 10^4)
```


